name: Cities API Image Builder

on:
  push:
    branches:
      - ccl-develop
  workflow_dispatch:

jobs:
  cities-indicator-api-build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Set Environment Variables
      - name: Set environment variables
        run: |
          echo "CITIES_API_AIRTABLE_KEY=${{ secrets.CITIES_API_AIRTABLE_KEY }}" >> $GITHUB_ENV
          echo "AIRTABLE_BASE_ID=${{ vars.AIRTABLE_BASE_ID }}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV

      # OIDC Assume Role
      - name: OIDC Assume Role
        id: oidc-assume-role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::540362055257:role/GitHubActionsOIDC
          aws-region: us-east-1

      # AWS ECR Login
      - name: ECR Login
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 540362055257.dkr.ecr.us-east-1.amazonaws.com

      # Docker Image Build
      - name: Build Docker image
        id: build-image
        run: |
          docker build -t ${{ env.REPOSITORY_NAME }}-img:latest .
          docker tag ${{ env.REPOSITORY_NAME }}-img:latest 540362055257.dkr.ecr.us-east-1.amazonaws.com/${{ env.REPOSITORY_NAME }}-img:latest

      # Push to ECR
      - name: Push to AWS ECR
        run: |
          docker push 540362055257.dkr.ecr.us-east-1.amazonaws.com/${{ env.REPOSITORY_NAME }}-img:latest

      # Deploy to AWS APP Runner
      - name: Deploy to App Runner
        id: deploy-apprunner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: cities-api-app-runner-service-Docker 
          image: 540362055257.dkr.ecr.us-east-1.amazonaws.com/${{ env.REPOSITORY_NAME }}-img:latest
          access-role-arn: arn:aws:iam::540362055257:role/cities-api-app-runner-docker
          region: us-east-1
          cpu: 1
          memory: 2
          wait-for-service-stability-seconds: 600

      # Cleanup Docker Image if Deploy Fails
      - name: Cleanup Docker Image on Failure
        if: failure()
        run: |
          REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          IMAGE_TAG=540362055257.dkr.ecr.us-east-1.amazonaws.com/${{ env.REPOSITORY_NAME }}-img:latest
          echo "Deleting Docker image from ECR: $IMAGE_TAG"
          aws ecr batch-delete-image --repository-name ${REPOSITORY_NAME}-img --image-ids imageTag=latest --region us-east-1