name: Deploy to AWS Develop Environment

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  ssh-deploy:
    name: ssh-deploy
    runs-on: ubuntu-20.04
    steps:
    - name: Deploy over ssh
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/cities-indicators-api
          git fetch --all
          git checkout develop
          git pull
          docker kill develop-container
          docker build . -t develop-image
          docker run -d --rm -p 8000:8000 --env-file ../.env --name develop-container develop-image
        