name: Unit Tests

on: 
  pull_request:
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CITIES_API_AIRTABLE_KEY: 'patsFvxGKOUr1DUPk.46471593dcc865c3335021a6f54dffb966907fedabb72b24881fe3da85a9a282'
      AIRTABLE_BASE_ID: 'appFGpvPnF6t7Uv5q'
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pipenv dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev --deploy --ignore-pipfile

    - name: Running unit tests
      env:
        PYTHONPATH: ./
      run: |
        pipenv run pytest -v -s tests/unit/
